### ISSUE TITLE
document (recommend) usage with npx

### ISSUE THREAD

**Issue by thescientist13** [juliangruber/test-npm-dependants#6]
Not sure if you are familiar with [**npx**](https://www.npmjs.com/package/npx), which is bundled with **npm**, but it's really good for running CLIs and similar "one-off" / one-time tools as an alternative to installing them globally.  It execute just as if you installed it globally, except that it cleans up all its dependencies after it has completed.

An example using the current steps in the README would look like this:
```shell
$ npx test-npm-dependants -v
```

Another advantage (depending on how you look at it is) is that with a global install, users will be responsible for upgrading their global install to use newer versions.  `npx` will always use the latest available pulled from the registry.

**Comment by juliangruber** [comment]
Thank you for creating this issue! I am aware of the npx tool, however I would discourage using this module without a containerization strategy. Running a lot of foreign code can open up your machine to a lot of security risks, see https://github.com/juliangruber/test-npm-dependants#security. So actually I don't want to make it too easy to run this. But thank you for your suggestion as with almost all other CLIs this would be the perfect thing to suggest :)

**Comment by thescientist13** [comment]
Ah, of course.  Totally makes sense.  Context is everything.  👍 

Thanks and good luck with the project!
